name: Upload to Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v2

      # 2. 必要な依存関係のインストール
      - name: Install dependencies
        run: |
          pip install huggingface_hub transformers

      # 3. Hugging Face Hubへのアップロード
      - name: Upload to Hugging Face Hub
        env:
          HFTOKEN: ${{ secrets.HFTOKEN }}  # Hugging Faceのトークン
        run: |
          # Hugging Face Hubにログイン
          huggingface-cli login --token $HFTOKEN

          # リポジトリの作成（必要に応じてコメントアウト）
          if huggingface-cli repo create repository-name --type=model; then
            echo "リポジトリを作成しました。"
          else
            echo "リポジトリはすでに存在します。"
          fi

          # リポジトリ全体のファイルをアップロード
          if huggingface-cli upload ./* --repo repository-name --all-files; then
            echo "ファイルをアップロードしました。"
          else
            echo "ファイルのアップロードに失敗しました。"
          fi
