name: Upload to Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install huggingface_hub transformers

      - name: Login to Hugging Face Hub
        env:
          HFTOKEN: ${{ secrets.HFTOKEN }}
        run: |
          echo "Logging in to Hugging Face Hub..."
          huggingface-cli login --token $HFTOKEN

      - name: Check if repo exists
        run: |
          echo "Checking if the repository exists..."
          if huggingface-cli repo info momonga.ai; then
            echo "リポジトリは既に存在します。"
          else
            echo "リポジトリが存在しないため、作成します..."
            huggingface-cli repo create momonga.ai --type=model
            echo "リポジトリを作成しました。"
          fi

      - name: Upload to Hugging Face Hub
        run: |
          echo "アップロードするファイル:"
          ls -la
          echo "Uploading files to Hugging Face Hub..."
          if huggingface-cli upload ./ --repo momonga.ai; then
            echo "ファイルをアップロードしました。"
          else
            echo "ファイルのアップロードに失敗しました。"
          fi
