name: Upload to Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install huggingface_hub transformers

      - name: Login to Hugging Face Hub
        env:
          HFTOKEN: ${{ secrets.HFTOKEN }}
        run: |
          echo "Logging in to Hugging Face Hub..."
          huggingface-cli login --token $HFTOKEN

      - name: Create repository if not exists
        run: |
          echo "Creating repository if it does not exist..."
          huggingface-cli repo create momonga-ai --type=model --yes || echo "リポジトリは既に存在します。"

      - name: Upload to Hugging Face Hub
        run: |
          echo "Uploading files to Hugging Face Hub..."
          echo "アップロードするファイル:"
          ls -la
          if huggingface-cli upload ./ --repo momonga-ai --repo-type=model --all-files; then
            echo "ファイルをアップロードしました。"
          else
            echo "ファイルのアップロードに失敗しました。"
            exit 1
          fi
