name: Upload to Hugging Face Hub

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pip install huggingface_hub transformers

      - name: Upload to Hugging Face Hub
        env:
          HFTOKEN: ${{ secrets.HFTOKEN }}
        run: |
          huggingface-cli login --token $HFTOKEN

          # リポジトリの作成（必要に応じてコメントアウト）
          if huggingface-cli repo create momonga.ai --type=model; then
            echo "リポジトリを作成しました。"
          else
            echo "リポジトリはすでに存在します。"
          fi

          # アップロード対象のファイルをリスト表示
          echo "アップロードするファイル:"
          ls -la

          # リポジトリ全体のファイルをアップロード
          if huggingface-cli upload ./* --repo momonga.ai --all-files; then
            echo "ファイルをアップロードしました。"
          else
            echo "ファイルのアップロードに失敗しました。"
          fi
